-- 1. Create the Teams table (Pure master data)
CREATE TABLE teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_name TEXT NOT NULL UNIQUE,
    city TEXT NOT NULL
);


CREATE TABLE players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT REFERENCES teams(id) NOT NULL
);


CREATE TYPE match_result AS ENUM ('w', 'd', 'l');

-- 2. Create the Matches table (Historical events and core engine data)
CREATE TABLE matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league TEXT NOT NULL,
    season VARCHAR(9) NOT NULL,
    match_date TIMESTAMP WITH TIME ZONE NOT NULL,
    
    -- Relational links to the teams table
    home_team_id BIGINT REFERENCES teams(id) NOT NULL,
    away_team_id BIGINT REFERENCES teams(id) NOT NULL,
    
    home_score SMALLINT,
    home_result  match_result,
    home_points SMALLINT,
    away_score SMALLINT,
    away_result  match_result,
    away_points SMALLINT,
    game_week SMALLINT,

    -- Business logic constraint: a team cannot play against itself
    CONSTRAINT check_different_teams CHECK (home_team_id <> away_team_id)
);

CREATE TYPE football_event AS ENUM ('goal', 'own_goal', 'yellow_card', 'red_card');

CREATE TABLE match_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT REFERENCES matches(id) NOT NULL,
    event_type football_event NOT NULL,
    player_id BIGINT REFERENCES players(id) NOT NULL,
    event_time INT NOT NULL
);

CREATE TYPE bet_prediction AS ENUM ('under', 'over', 'goal', 'no_goal');
CREATE TYPE accuracy AS ENUM ('low', 'medium', 'high');

CREATE TABLE predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT REFERENCES matches(id) NOT NULL,
    prediction bet_prediction NOT NULL,
    prediction_result BOOLEAN,
    prediction_accuracy accuracy NOT NULL
);


-- 3. Performance optimization: Explicit index creation
-- Allows Postgres to instantly filter by league and season without full table scans
CREATE INDEX idx_matches_league_season ON matches(league, season);
CREATE INDEX idx_matches_home_team ON matches(home_team_id);
CREATE INDEX idx_matches_away_team ON matches(away_team_id);

ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.match_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.predictions ENABLE ROW LEVEL SECURITY;